### PR TITLE
Preparatory instructions

### PR DESCRIPTION
**Pull request by alectunbridge**
All I've done is move the instructions to the end of the slides and added some friable links to it (happy to be told there's a better way).
Also I've put a note in re Miro.
We could do with instructions for the other langs but probably a bit late in the day at this point and better to get it out there.

### CODE REVIEW

**Comment by mrmanc** [comment]
Awesome. I think the Java instructions are a little out of date though… I haven’t checked but from memory it is fine to ‘open’ the project rather than importing it. We currently don’t tell them how to clone the project. That means that some people use something like IntelliJ to clone it, which then opens it in the root. We should explicitly tell them to run the git command on the command line I think, and then be clear about opening the subdirectory as appropriate. For languages other than Java there is nothing explicit telling them to use the subdirectory at the moment.

I agree with the concern about breaking the link—particularly as we have changes to make to the slides still. I might be able to find a way to include the file from an external markdown file, so we could distribute a link to the static file which wouldn’t break. I’ll have a play with what you have done now.

**Comment by mrmanc** [comment]
Alternatively… [this](https://revealjs.com/links/) might be an option.

**Comment by alectunbridge** [comment]
> Alternatively… [this](https://revealjs.com/links/) might be an option.

Unfortunately I don't think that works for files outside of the _slideshow_.

**Comment by mrmanc** [comment]
Got it working—can’t find a way to feed an id to the slide as suggested, but you can link to any heading’s id—so just link to the id of the heading on the page (`preparatory-instructions-for-apprentices`) and that works 😃 

e.g. http://localhost:4000/#/preparatory-instructions-for-apprentices

**Pull request merged**
